# Generated by Django 2.2.5 on 2019-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=50)),
                ('brief_description', models.TextField(max_length=200)),
                ('status', models.BooleanField()),
                ('project_details', models.TextField()),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
