# Generated by Django 2.2.5 on 2019-10-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='ongoing',
        ),
    ]
