# Generated by Django 2.2.5 on 2019-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0002_auto_20191022_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/manna/img'),
        ),
    ]
