# Generated by Django 2.2.5 on 2019-10-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0005_auto_20191022_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brief_description',
            field=models.TextField(max_length=100),
        ),
    ]
