# Generated by Django 2.2.5 on 2019-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0006_auto_20191022_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='community',
            field=models.CharField(max_length=60),
        ),
    ]
