# Generated by Django 2.2.5 on 2019-10-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0007_auto_20191022_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_No',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
