# Generated by Django 2.2.5 on 2019-10-22 10:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0009_auto_20191022_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_no',
            name='p_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
