# Generated by Django 2.2.5 on 2019-10-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0012_auto_20191022_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manna_Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.TextField()),
                ('what_we_do', models.TextField()),
                ('get_in_touch', models.TextField()),
            ],
        ),
    ]
