# Generated by Django 2.2.5 on 2019-10-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0013_manna_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manna_Home',
        ),
    ]
