# Generated by Django 2.2.5 on 2019-12-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0014_delete_manna_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to='manna'),
        ),
    ]
