# Generated by Django 2.2.5 on 2019-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0015_auto_20191216_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('naira_number', models.CharField(max_length=20)),
                ('dollar_number', models.CharField(max_length=20)),
                ('pound_number', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=100)),
            ],
        ),
    ]
