# Generated by Django 2.2.5 on 2019-12-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0016_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dollar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pound_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
